### ISSUE TITLE
NaN passes as true

### ISSUE THREAD

**Issue by bsiddiqui** [leecrossley/isNumeric#2]
``` js
require('is-numeric')(NaN) // => true
```

**Comment by leecrossley** [comment]
I'm not sure how you're testing this, but this simply isn't the case. There's also a test case for it in the specs that passes and asserts that it is false. https://github.com/leecrossley/isNumeric/blob/master/spec.js#L95

I suggest you look at your implementation.

**Comment by bsiddiqui** [comment]
@leecrossley my bad, was using npm.com/is-numeric instead of npm.com/isnumeric

**Comment by leecrossley** [comment]
No problem, you should probably use this package, as it's well tested and has been in production over 2 years.

**Comment by bsiddiqui** [comment]
Yeah definitely, have used it for a while. Messed up the install on a new
project. Thanks for the awesome package. Cheers.
